package com.programacion.web.data.dto;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;

@Entity
@Table(name = "users")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // corresponds to GENERATED BY DEFAULT AS IDENTITY
    @Column(name = "id", nullable = false)
    private Integer id;

    @Column(name = "name", nullable = false, length = 255)
    private String name;

    @Column(name = "username", nullable = false, length = 255)
    private String username;

    @Column(name = "email", nullable = false, length = 255)
    private String email;

    @Column(name = "address_street", length = 255)
    private String addressStreet;

    @Column(name = "address_suite", length = 100)
    private String addressSuite;

    @Column(name = "address_city", length = 100)
    private String addressCity;

    @Column(name = "address_zipcode", length = 20)
    private String addressZipcode;

    @Column(name = "address_geo_lat", precision = 10, scale = 7)
    private BigDecimal addressGeoLat;

    @Column(name = "address_geo_lng", precision = 10, scale = 7)
    private BigDecimal addressGeoLng;

    @Column(name = "phone", length = 50)
    private String phone;

    @Column(name = "website", length = 255)
    private String website;

    @Column(name = "company_name", length = 255)
    private String companyName;

    @Column(name = "company_catch_phrase", columnDefinition = "text")
    private String companyCatchPhrase;

    @Column(name = "company_bs", length = 255)
    private String companyBs;



}